//! Minimal test harness for Hadron OS userspace tests.
//!
//! Provides [`run_utests`] and the [`utest_main!`] macro for writing
//! `#![no_std]` test binaries that run as PID 1 under the kernel's
//! `--utest` mode.
//!
//! # How it works
//!
//! The kernel's `--utest` cmdline flag causes PID 1's exit code to be
//! forwarded to the `isa-debug-exit` device (ring-0 privilege). Userspace
//! tests call [`run_utests`], which exits with 0 on all-pass or 1 on failure.
//! The kernel then signals QEMU exit code 33 (pass) or 35 (fail).
//!
//! # Usage
//!
//! ```ignore
//! #![no_std]
//! #![no_main]
//! use hadron_utest::utest_main;
//!
//! utest_main!(test_one, test_two);
//!
//! fn test_one() { assert_eq!(1 + 1, 2); }
//! fn test_two() { /* ... */ }
//! ```

#![no_std]

use hadron_syscall::wrappers::{sys_debug_log, sys_task_exit};

/// ELF entry point.
///
/// Aligns the stack and calls into `__utest_main`, which is generated by
/// the [`utest_main!`] macro in the test binary.
#[unsafe(no_mangle)]
#[unsafe(naked)]
pub extern "C" fn _start() -> ! {
    // SAFETY: Aligns stack to 16-byte boundary per System V ABI before calling
    // into Rust. No stack frame is needed for the naked function itself.
    core::arch::naked_asm!(
        "and rsp, -16",
        "call {entry}",
        entry = sym _utest_entry,
    );
}

/// Calls the test binary's `__utest_main` function.
///
/// This indirection keeps `_start` naked and allows `__utest_main` to be
/// a regular function generated by [`utest_main!`] in the test binary.
unsafe extern "C" {
    /// Generated by [`utest_main!`] in the test binary.
    ///
    /// # Safety
    ///
    /// This function must be defined by [`utest_main!`] in the linked test
    /// binary. Calling it when no such definition exists is undefined behavior.
    fn __utest_main() -> !;
}

fn _utest_entry() -> ! {
    // SAFETY: __utest_main is defined by utest_main! in the test binary
    // linked with this library. The linker ensures the symbol is present.
    unsafe { __utest_main() }
}

/// Write a string slice to the kernel debug log (fd 1 equivalent).
fn debug_write(s: &str) {
    let buf = s.as_bytes();
    // SAFETY: buf points to a valid byte slice; sys_debug_log copies it.
    sys_debug_log(buf.as_ptr() as usize, buf.len());
}

/// Run a list of test functions and exit with 0 (pass) or 1 (fail).
///
/// Each test is called in order. If a test panics, the panic handler calls
/// `sys_task_exit(1)` immediately, which the kernel (in `--utest` mode)
/// maps to QEMU exit 35 (failure). Tests that return normally are considered
/// passing. After all tests pass, exits with 0 (QEMU exit 33).
pub fn run_utests(tests: &[(&str, fn())]) -> ! {
    for (name, f) in tests {
        debug_write("test ");
        debug_write(name);
        debug_write(" ... ");
        f();
        // If f() returned, the test passed (panics cause immediate exit).
        debug_write("ok\n");
    }

    debug_write("all tests passed\n");
    sys_task_exit(0);
    // sys_task_exit diverges; this is unreachable.
    #[allow(clippy::empty_loop)]
    loop {}
}

/// Define the test binary's entry point and wire up all test functions.
///
/// Generates `__utest_main` (called by [`_start`] in this library) and
/// passes all listed test functions to [`run_utests`].
///
/// # Example
///
/// ```ignore
/// utest_main!(test_one, test_two);
/// ```
#[macro_export]
macro_rules! utest_main {
    ($($test:ident),* $(,)?) => {
        #[unsafe(no_mangle)]
        pub extern "C" fn __utest_main() -> ! {
            $crate::run_utests(&[$((stringify!($test), $test),)*])
        }
    };
}

/// Panic handler: log a message and exit with failure.
///
/// Panics in test functions cause the process to exit with 1, which the
/// kernel (in `--utest` mode) maps to QEMU exit code 35 (failure).
#[panic_handler]
fn panic(info: &core::panic::PanicInfo<'_>) -> ! {
    debug_write("PANIC: ");
    // Format the panic message manually since we're no_std.
    if let Some(msg) = info.message().as_str() {
        debug_write(msg);
    } else {
        debug_write("(no message)");
    }
    debug_write("\n");
    sys_task_exit(1);
    loop {}
}
