[package]
name = "hadron-kernel-image"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "hadron-kernel-image"
path = "src/main.rs"
test = false
bench = false
doctest = false

[dependencies]
hadron-kernel = { workspace = true }

[lints]
workspace = true
