[package]
name = "hadron-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
# Integration tests are QEMU-only (built by gluon, not cargo).
autotests = false

[lib]
bench = false
doctest = false

[dependencies]
bitflags = { workspace = true }
hadron-arch-x86_64 = { workspace = true }
hadron-boot-info = { workspace = true }
hadron-core = { workspace = true }
hadron-intrinsics = { workspace = true }
hadron-ktest = { workspace = true }
hadron-mm = { workspace = true }
hadron-vfs-protocol = { workspace = true }
planck-noalloc = { workspace = true }

[dev-dependencies]
hadron-bench = { workspace = true }
hadron-test = { workspace = true }
planck-noalloc = { workspace = true }

[lints]
workspace = true
